// utils.js (optional - only if used elsewhere)
export function humanizeText(aiText) {
  return aiText
    .replace(/AI thinks.../g, "In my opinion,")
    .replace(/\[Local Processing\]/g, "(Generated by AI, refined)");
}
